// Generated by CoffeeScript 1.10.0
(function() {
  var bappHost, c, contractName, formElem, getParam, info, mailHost, mailUrl, methodPost, postJSON, setLoaded, setLoading, spinner, submit;

  bappHost = "bapp.ab.mkvd.net";

  mailHost = document.location.hostname === "localhost" ? "localhost:3001" : "mail_tally.ab.mkvd.net";

  contractName = 'contact_form';

  c = console || {
    log: function() {}
  };

  mailUrl = "http://" + mailHost + "/mail";

  methodPost = function(name) {
    var host;
    host = "http://" + bappHost;
    return host + "/api/" + contractName + "/" + name;
  };

  postJSON = function(url, params, callback) {
    return $.post(url, params, callback, 'json');
  };

  formElem = $("form#contact");

  getParam = function(param, params) {
    var par;
    par = _(params).find(function(p) {
      return p.name === param;
    });
    return par.value;
  };

  spinner = $(".spinner");

  info = $(".message");

  submit = $("form#contact input[type='submit']");

  setLoading = function() {
    submit.attr("disabled", true);
    spinner.css({
      visibility: "visible"
    });
    return info.html("loading...");
  };

  setLoaded = function(contract_address) {
    spinner.css({
      visibility: "hidden"
    });
    return info.html("We have received your message and we'll contact you shortly.");
  };

  formElem.on("submit", function(evt) {
    var body, email, firstName, lastName, mailArgs, message, params, values;
    evt.preventDefault();
    setLoading();
    params = formElem.serializeArray();
    email = getParam("email", params);
    firstName = getParam("first", params);
    lastName = getParam("last", params);
    message = getParam("message", params);
    message = message.split("\n").join("<br>");
    body = message;
    values = {
      values: [email, firstName, lastName],
      types: ["bytes32", "bytes32", "bytes32"]
    };
    if (email) {
      c.log("addContact(" + (values.values.join(", ")) + ") called!");
      mailArgs = {
        from_name: firstName + " " + lastName + " <" + email + ">",
        from_address: email,
        body: body
      };
      postJSON(mailUrl, mailArgs, function(resp) {
        if (resp.success) {
          c.log("Email sent!");
          return setLoaded();
        }
      });
      return postJSON(methodPost("addContact"), values, function(resp) {
        c.log("addContact() //=> '" + (JSON.stringify(resp)) + "'");
        if (resp.success) {
          return c.log("Success!!");
        }
      });
    }
  });

}).call(this);
